### ISSUE TITLE
some problem in dataset_tool.py 

### ISSUE THREAD

**Issue by jexz11** [drboog/Lafite#1]
<img width="701" alt="1647183764(1)" src="https://user-images.githubusercontent.com/76417800/158065926-f02c92ce-4b49-45ea-b472-c143d7470ef5.png">

I don't know why this program is running so slow. is there anything I can do to speed up the process?

PS：Due to personal habits, I used to run my code on Jupyter Notebook, but I still couldn't run it on Jupyter Notebook when all the packages were installed successfully and the function didn't have any problems, but I could run it on CMD (albeit slowly). May I ask what is the reason for this?

**Comment by jexz11** [comment]
<img width="673" alt="1647184364(1)" src="https://user-images.githubusercontent.com/76417800/158066426-38462884-a2a6-4272-a5cb-66ff320ec389.png">

The code I had the problem with on the Jupyter Notebook reads like this

**Comment by jexz11** [comment]
<img width="698" alt="1647184669(1)" src="https://user-images.githubusercontent.com/76417800/158066574-b696b0fb-f612-4b9c-831f-16766d63f509.png">
Ok, new problem appears, let me eliminate it!!LOL

**Comment by drboog** [comment]
It will first download the pre-trained CLIP model (which is 338M shown in your figure I think) before processing the dataset, so internet connection matters here. The actual processing time depends on the dataset size and what GPU you are using, normally it should be less than few hours.

**Comment by jexz11** [comment]
Thank you for your reply！！！！（Will it help if I use VPN to download it? But there's another aspect of the problem:Model has been downloaded but the SHA256 checksum does not not match.I'll try to solve this problem tomorrow

**Comment by jexz11** [comment]
\(^o^)/~The problem is solved~~~~~~
