### ISSUE TITLE
Pretrained language free MM CelebA-HQ model

### ISSUE THREAD

**Issue by justinpinkney** [drboog/Lafite#13]
Hi I'm currently putting together a paper on a different language free text-to-image generation method and I was wondering if you had the pre-trained celebA hq model that you could share with me for comparison purposes?

**Comment by justinpinkney** [comment]
Thank you, exactly what I was looking for!

**Comment by YeolJ00** [comment]
Hi, I tried inferencing with the checkpoints you provided and somehow I mostly get male images even in cases where the text description points to female (e.g., "She is wearing lipstick").
So the FID-30k (which should be lower than the 6k version) goes up to about 54 despite the high quality images. 
Is this a known issue? or do I need another checkpoint?

Thanks in advance!

**Comment by YeolJ00** [comment]
Oops, it was a simple inference issue. My apologies
