### ISSUE TITLE
FID evaluation

### ISSUE THREAD

**Issue by yrcong** [drboog/Lafite#14]
Hi,

i tried to evaluate the model with the command:
``python calc_metrics.py --network=./some_pre-trained_models.pkl --metrics=fid50k_full,is50k --data=./training_data.zip --test_data=./testing_data.zip``

I found in the function ``compute_feature_stats_for_dataset`` in ``metric_utils.py``, the training images are used, not the test images.
It makes me confused. Did I make some mistakes or it is what you want to implement?

I think the features of the test images should be computed for FID.

best

**Comment by drboog** [comment]
Hi, you can use "--data=./testing_data.zip --test_data=./testing_data.zip". 
The reason of having two arguments here is I think previous papers are not very clear and consistent on computing metrics. In other words, should we evaluate all the models under "training vs generated images" or "testing vs generated images"?
If I remember correctly, these two ways have FID difference of ~0.2 on MS-COCO.

**Comment by yrcong** [comment]
I think we should compare with the test images since the captions in the training/test set could be different.
thanks for the reply:)
