### ISSUE TITLE
Some questions about the experimental setting

### ISSUE THREAD

**Issue by Yongssss** [drboog/Lafite#20]
Thanks for your excellent work. By the way, Happy Mid Autumn Festival.
I have some questions about the experimental setting.
1. How many times have you run Lafite on COCO in a supervision manner? And do you report the best FID 8.12 out of all runs?
2. How do you pre-process the original images in COCO to 256x256 resolution? Interpolation or Center-crop?

**Comment by drboog** [comment]
Happy Mid Autumn Festival.
1. At the time of submission, I only run the experiment once (with 25000 kimg), and report that result. Actually, that results in the paper is not the best results the model can get. If you continue training, the performance will be slightly improved. See jnhwkin's reproduced result at https://github.com/drboog/Lafite/issues/4.  
2. The COCO images are center cropped and resized to 256*256.
