### ISSUE TITLE
The questions about parameters img_img_c and img_img_d

### ISSUE THREAD

**Issue by Yongssss** [drboog/Lafite#22]
Thank you very much for your work. I have some confusion when I read the source code. 

Why did you set the parameters img_img_c and img_img_d to 0? Are they good for FID and IS of Lafite on COCO?

**Comment by drboog** [comment]
They are for image-image contrastive losses. I keep them in the code in case someone need them.

Basically I wrote 4 contrastive losses, 2 of them are image-text contrastive losses (img_txt_c and img_txt_d), the other 2 are image-image contrastive losses (img_img_c and img_img_d). We found that image-text contrastive losses are more important, thus I set img_img_c and img_img_d to be 0, and only tune img_txt_c and img_txt_d for simplicity.

I'm not saying that image-image contrastive losses are not helpful, you can try to tune them to see whether they can lead to improvement, I just set them to be 0 to focus on image-text contrastive losses.
