### ISSUE TITLE
Question about FID-k

### ISSUE THREAD

**Issue by kminsoo** [drboog/Lafite#27]
Hi authors,

Again, I really appreciate you for sharing your codes.
I would like to ask a question about FID-k.
As written in your paper, FID-k means the FID is computed after blurring all the images by a Gaussian filter with radius k.

In the sentence, what is the value of sigma for the Gaussian filter? (sigma is the hyperparameter about torchvision.transforms.GaussianBlur which is described in https://pytorch.org/vision/stable/generated/torchvision.transforms.GaussianBlur.html )

**Comment by kminsoo** [comment]
Or, could you share the code for measuring FID-k not FID-0?

**Comment by drboog** [comment]
I think I followed some previous work (not sure which one exactly), use
$\sigma=\sqrt{(((k*2+1)^2 - 1)/12)}$
and
T.GaussianBlur(kernel_size=(1+2k, 1+2k), sigma= $\sigma$ )

**Comment by kminsoo** [comment]
Thank you for answering!
