### ISSUE TITLE
Pre-trained Model on CUB dataset

### ISSUE THREAD

**Issue by Kilichbek** [drboog/Lafite#29]
Hi, 
Thanks for the nice work! Is it possible to provide pre-trained models on the CUB dataset?
It would be helpful. Thanks

Best,
Kilichbek

**Comment by drboog** [comment]
Hi,
In the experiments of CUB, best FID and IS I got corresponding to different checkpoints. Here are some checkpoints I found which might be useful to you.

https://drive.google.com/file/d/14B9kYfEBywc3uNlQF89D3BeXk-PrjwAE/view?usp=share_link
https://drive.google.com/file/d/1StYlf3gLoHiWPfdLmdg6idoWl_zTj5d9/view?usp=share_link
https://drive.google.com/file/d/1nD5PlrXhz-9U3stO16i9c6qvtc5wkSzl/view?usp=share_link

**Comment by Kilichbek** [comment]
Thank you very much!
