### ISSUE TITLE
Pretrained checkpoints for MM-CelebA-HQ

### ISSUE THREAD

**Issue by YeolJ00** [drboog/Lafite#31]
Hi,
The checkpoints that you have already shared is a great help to the project I'm working on.
Can you provide the checkpoints for the MM-CelebA-HQ trained from scratch?

Thanks!

**Comment by drboog** [comment]
I have some checkpoints, for both language-free and supervised settings.

https://drive.google.com/file/d/1wFF1BXxuxKXjuhzEx4a2SqnEQ5gimypc/view?usp=sharing

https://drive.google.com/file/d/1LwKhpYW5SM1m_Dqpn0kigMBT2bEVywDD/view?usp=sharing

https://drive.google.com/file/d/1LwKhpYW5SM1m_Dqpn0kigMBT2bEVywDD/view?usp=sharing


Checkpoints from https://arxiv.org/abs/2210.14124:

https://drive.google.com/file/d/1pO8PRcJdYBwQib_S8XOtXyBFPG-bcNru/view?usp=sharing

https://drive.google.com/file/d/1yzUoiyZDUWpmJP7rtyXrgKYonGSX2Yv7/view?usp=sharing
