### ISSUE TITLE
About generated results

### ISSUE THREAD

**Issue by victorup** [drboog/Lafite#33]
Hi, 
I used the COCO2014_CLIP_ViTB32_all_text.pkl file to infer images based on the text 'A city street line with brick buildings and trees.' However, the results I obtained were inferior, as shown in the following image.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/44796817/233528403-28e5c4bd-0065-4aa5-b268-c276091e4d1f.png">

**Comment by drboog** [comment]
This is what I got with the same checkpoint. 

Of course, the results will be worse than [diffusion model](https://github.com/drboog/Shifted_Diffusion), but your results means there is something wrong in your testing implementation.

<img src=https://user-images.githubusercontent.com/47047889/233609604-809de03e-d326-4f61-a682-71ad6803b37f.png  width="300" height="300" />

**Comment by victorup** [comment]
I have reviewed my inference code and discovered that I mistakenly loaded the ViT-B/16 clip model instead of the ViT-B/32. Thanks for your help!
