### ISSUE TITLE
pretrained model link

### ISSUE THREAD

**Issue by sklin93** [drboog/Lafite#8]
Hi, the [Model trained on MS-COCO with Ground-truth Image-text Pairs, CLIP-ViT/B-16](https://drive.google.com/file/d/17ER7Yl02Y6yCPbyWxK_tGrJ8RKkcieKq/view?usp=sharing) is actually linked to the same link as [Model Pre-trained On Google CC3M](https://drive.google.com/file/d/17ER7Yl02Y6yCPbyWxK_tGrJ8RKkcieKq/view?usp=sharing) in the README. Could you update the correct ViT/B-16 model link? Thank you so much!

**Comment by drboog** [comment]
Thanks for pointing it out, I have updated the link.

**Comment by sklin93** [comment]
Thank you for the quick update!
